Map.Site/Models/ErrorViewModel.cs
namespace Map.Site.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Map.Site/ViewModels/MapViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Map.Site.ViewModels
{
    public class MapViewModel
    {
        [Display(Name = @"Location")]
        [Required]
        public string Location { get; set; } = "London";

        public string Latitude { get; set; } = "51.47813";
        public string Longitude { get; set; } = "-0.09898";
    }
}

Map.Site/Controllers/HomeController.cs
using Map.Site.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Map.Site.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Map.Site/Controllers/MapController.cs
using Map.Library;
using Map.Site.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Map.Site.Controllers
{
    public class MapController : Controller
    {
        private readonly IMapReader _mapReader;

        public MapController(IMapReader mapReader)
        {
            _mapReader = mapReader;
        }

        public IActionResult Index()
        {
            var result = new MapViewModel();
            return View(result);
        }

        public ActionResult GetLocation(MapViewModel map)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", map);
            }

            var result = _mapReader.GetGeoLocation(map.Location);

            map.Latitude = result.Results.Select(x => x.Geometry.Lat).FirstOrDefault();
            map.Longitude = result.Results.Select(x => x.Geometry.Lng).FirstOrDefault();

            return View("Index", map);
        }
    }
}

Map.Site/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Map.Site/Views/Map/Index.cshtml
@model Map.Site.ViewModels.MapViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <style>
        /* Set the size of the div element that contains the map */
        #map {
            height: 400px; /* The height is 400 pixels */
            width: 100%; /* The width is the width of the web page */
        }
    </style>
</head>

<body>
    @using (Html.BeginForm("GetLocation", "Map"))
    {
        @Html.ValidationSummary(true, "Please fix the following errors.")
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">

                    @Html.TextBoxFor(m => m.Location, new { @class = "form-control", style = "width:350px;" })
                    @Html.ValidationMessageFor(m => m.Location)

                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Go!</button>
                </div>
            </div>
        </div>
    }

    <!--The div element for the map -->
    <div id="map"></div>
    <script>
        // Initialize and add the map
        function initMap() {

            var lo = @Html.ViewData.Model.Longitude;
            var la = @Html.ViewData.Model.Latitude;

            var destination = { lat:  Number(la), lng: Number(lo)};

            var map = new window.google.maps.Map(document.getElementById('map'), { zoom: 12, center: destination });

// ReSharper disable once UnusedLocals
            var marker = new window.google.maps.Marker({ position: destination, map: map, title: "Longitude: " + lo.toString() + " Latitude: " + la.toString() });

        }
    </script>


    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5l-3NS31trWbphIePZQuAYb95isX1i9E&callback=initMap">
    </script>
</body>
</html>

Map.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyMap.Site</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Map Application</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Map</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Map.Site - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>